### ISSUE TITLE
Reject String

### ISSUE THREAD

**Issue by adriamt** [andycandy-de/SimpleAndroidBridge#2]
Hi! I found your library and it was just what I needed, thanks !!

I have one question and it's if there is a way to reject with only a String instead of an Exception or if is not, how can I get the error from JS, because I only need to catch the reason of the reject, just the reason, not other string like "Error caused by ....".

Thanks

**Comment by andycandy-de** [comment]
Hello,

I am happy that you like it. It's designed to reject an exception. In the JS world you will get a ```NativeError``` https://github.com/andycandy-de/SimpleAndroidBridge/blob/development/SimpleAndoirdBridgeLibJS/src/main/js/init.js
You can access the ```nativeMessage``` field which is the message you instantiated the exception in kotlin.

e.g.

```
//kotlin
class AndroidNativeInterface(val contactService: ContactService): DefaultJSInterface("Android") {

    @NativeCall(CallType.FULL_PROMISE)
    fun searchContact(contactFilter: ContactFilter) = doInBackground<List<Contact>> { promise ->
        try {
            promise.resolve(contactService.search(contactFilter))
        } catch (e: Exception) {
            promise.reject(Exception("Any String Message!!!", e))
        }
    }
}
```

```
// Javascript
Bridge.interfaces.Android.searchContact({surname: "Pitt"}).then((list) => {
    console.log(list);
}).catch((e) => {
    console.log(e.nativeMessage); // the nativeMessage should be 'Any String Message!!!'
});
```

**Comment by adriamt** [comment]
Oh yeah!! Thanks !! It worked!

I've had done some tests and I had accomplished it too by declaring new classes using a String instead of an Exception but I was a mess and ugly.

with `nativeMessage` it worked like charm.
