### ISSUE TITLE
Support ProGuard

### ISSUE THREAD

**Issue by danqing** [andycandy-de/SimpleAndroidBridge#4]
Hi! Thank you for this great lib.

It looks like it's not compatible with ProGuard — I need to add the following line to my proguard rules for it to work properly:

```
-keep class de.andycandy.android.** { *; }
```

Can we make it such that it works with ProGuard out of the box? Thank you!

**Comment by andycandy-de** [comment]
Thank you for your feedback. I am happy when you enjoy my lib. Just one question beside the toppic. Which features do you use and how they work for you? I tried to design everything to be as simple as possible.

I don't know ProGuard well. Do you know how it works? Just let me know what I have to change or you can create a 'Pull Request' whit the changes if you want ☺

**Comment by andycandy-de** [comment]
Solved with the last release [1.1.0](https://github.com/andycandy-de/SimpleAndroidBridge/releases/tag/1.1.0)

**Comment by baconz** [comment]
I don't think this quite works yet. We need to tell progaurd to keep anything annotated with `@NativeCall`. To do this we need:

```
-keepclassmembers class * {
    @de.andycandy.android.bridge.NativeCall <methods>;
}
```

**Comment by andycandy-de** [comment]
So the [rules defined in version 1.1.2](https://github.com/andycandy-de/SimpleAndroidBridge/blob/1.1.2/SimpleAndroidBridgeLib/consumer-rules.pro) aren't enough?

```
-keepattributes Signature
-keepattributes Exceptions
-keepattributes SetJavaScriptEnabled
-keepattributes JavascriptInterface
-keepattributes InlinedApi
-keepattributes SourceFile,LineNumberTable
-keepattributes *Annotation*

-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}

-keep class de.andycandy.android.bridge.** {*;}
```

**Comment by andycandy-de** [comment]
> I don't think this quite works yet. We need to tell progaurd to keep anything annotated with `@NativeCall`. To do this we need:
> 
> ```
> -keepclassmembers class * {
>     @de.andycandy.android.bridge.NativeCall <methods>;
> }
> ```

Okay, I think ProGuard is removing the methods in your implementation. The code from the library should be fine. I'm not sure if the library should or can influence the ProGuard behavior of your codebase.
