### ISSUE TITLE
AWAIT

### ISSUE THREAD

**Issue by iraunit** [andycandy-de/SimpleAndroidBridge#5]
Could you give me an example to use this to fetch some data from API using async and await in the Javascript after a URL is loaded in the web view?
That will be really helpful.

**Comment by andycandy-de** [comment]
Look at the `Share Promise` example [( https://github.com/andycandy-de/SimpleAndroidBridge#share-promise )](https://github.com/andycandy-de/SimpleAndroidBridge#share-promise)

Async and await is just another way to work with promise. So it also works well:
```javascript
async function searchContact(filter) {
    const list = await Bridge.interfaces.Android.searchContact(filter);
    console.log(list);
    return list;
}
```

The android native function has to be marked as `CallType.FULL_PROMISE`
```kotlin
class AndroidNativeInterface(val contactService: ContactService): DefaultJSInterface("Android") {

    @NativeCall(CallType.FULL_PROMISE)
    fun searchContact(contactFilter: ContactFilter) = doInBackground<List<Contact>> { promise ->
        try {
            promise.resolve(contactService.search(contactFilter))
        } catch (e: Exception) {
            promise.reject(e)
        }
    }
}
```

Do you have any more questions?

**Comment by iraunit** [comment]
Thank you for replying.
I want something like this to call from my wevbiew console:

async function postData(url = "", data = {}) {
  // Default options are marked with *
  const response = await fetch(url, {
    method: "POST", // *GET, POST, PUT, DELETE, etc.
    mode: "cors", // no-cors, *cors, same-origin
    cache: "no-cache", // *default, no-cache, reload, force-cache, only-if-cached
    credentials: "same-origin", // include, *same-origin, omit
    headers: {
      "Content-Type": "application/json",
      // 'Content-Type': 'application/x-www-form-urlencoded',
    },
    redirect: "follow", // manual, *follow, error
    referrerPolicy: "no-referrer", // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
    body: JSON.stringify(data), // body data type must match "Content-Type" header
  });
  return response.json(); // parses JSON response into native JavaScript objects
}

**Comment by andycandy-de** [comment]
If I understand you well you want to request a web api. This lib is implemented to simplify the communication between webview and native android. But your code snippet implements a communication between webview and webserver.
If so this lib is not what you want. Please check out the fetch api (https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)

**Comment by iraunit** [comment]
Thank you ☺
