### ISSUE TITLE
NativeCall CallType differences

### ISSUE THREAD

**Issue by esqi** [andycandy-de/SimpleAndroidBridge#6]
Could you add explanation about CallType differences for NativeCall annotation in your `README.md`

**Comment by andycandy-de** [comment]
@esqi is the explanation I added with #7 enough?
https://github.com/andycandy-de/SimpleAndroidBridge/blob/fcf08fd59f4726ad26d5f4a18db3bf7e31181e00/README.md

**Comment by esqi** [comment]
LGTM
